config/routes.rb
Rails.application.routes.draw do
  devise_for :vendors, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  get 'connect_to_stripe', to: 'vendor_onboarding#connect_to_stripe'
  get 'stripe_connect_confirmation', to: 'vendor_onboarding#stripe_connect_confirmation'
  get 'confirmation_invoice_subscription', to: 'subscriptions#confirmation'

  resources :invoices do
    resources :subscriptions, only: [:new, :create, :confirmation]
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :vendor
  has_many :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :invoice
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:stripe_connect]

  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_vendor!

  def index
    @invoices = current_vendor.invoices
  end

  def new
    @invoice = current_vendor.invoices.build
  end

  def create
    @invoice = current_vendor.invoices.build(invoice_params)
    response = create_stripe_plan(current_vendor, @invoice)
    @invoice.id_for_plan = response.id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: 'Invoice successfully created!' }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def invoice_params
      params.require(:invoice).permit(:name, :description, :amount)
    end

    def create_stripe_plan(vendor, invoice)
      Stripe::Plan.create(
        {
          amount: invoice.amount * 100,
          interval: 'month',
          name: invoice.name,
          currency: 'usd',
          id: invoice.name + Invoice.maximum(:id).to_i.next.to_s
        },
        stripe_account: vendor.stripe_uid
      )
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def stripe_connect
    @vendor = current_vendor
    if @vendor.update_without_password({
      provider: request.env['omniauth.auth'].provider,
      stripe_uid: request.env['omniauth.auth'].uid,
      stripe_access_token: request.env['omniauth.auth'].credentials.token,
      stripe_refresh_token: request.env['omniauth.auth'].credentials.token,
      stripe_publishable_key: request.env['omniauth.auth'].info.stripe_publishable_key
    })
      # anything else you need to do in response..
      redirect_to stripe_connect_confirmation_path,
        notice: 'Congrats on connecting your Stripe account!'
    else
      redirect_to connect_to_stripe_path,
        alert: 'Please connect to Stripe before you can continue.'
    end
  end

  def failure
    redirect_to connect_to_stripe_path, alert: 'Stripe returned an error message: ' + params[:error_description]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    connect_to_stripe_path
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    @invoice = Invoice.find(params[:invoice_id])
    @subscription = @invoice.subscriptions.build
    vendor = @invoice.vendor
    connected_stripe_account = Stripe::Account.retrieve(vendor.stripe_uid)
    @business_name = connected_stripe_account.business_name
    @statement_descriptor = connected_stripe_account.statement_descriptor
  end

  def create
    @invoice = Invoice.find(params[:invoice_id])

    if params[:stripeToken]
      @subscription = @invoice.subscriptions.build(subscription_params)
      @token = params[:stripeToken]
      vendor = @invoice.vendor
      @stripe_account = vendor.stripe_uid
      @create_customer_response = create_customer(@subscription.customer_email, @token, @stripe_account)
      @create_subscription_response = create_subscription(@create_customer_response.id, @invoice.id_for_plan, @stripe_account)

      @subscription.id_for_customer = @create_customer_response.id
      @subscription.id_for_subscription = @create_subscription_response.id
      respond_to do |format|
        if @subscription.save
          format.html { redirect_to confirmation_invoice_subscription_path(@invoice, @subscription) }
        else
          format.html { render :new }
          format.json { redner json: @subscription.errors, status: :unprocessable_entity }
        end
      end
    end
  rescue Exception => e
    flash[:alert] = 'Sorry we encountered an error: ' + e.message
    redirect_to new_invoice_subscription_path(@invoice)
  end

  def confirmation
  end

  private
    def subscription_params
      params.require(:subscription).permit(:invoice_id, :customer_email)
    end

    def create_customer(email, token, stripe_account)
      Stripe::Customer.create(
        {
          description: 'Gigtilt customer ' + email,
          source: token
        },
        {stripe_account: stripe_account}
      )
    end

    def create_subscription(customer, plan, stripe_account)
      Stripe::Subscription.create(
        {
          customer: customer,
          items: [{plan: plan}]
        },
        {stripe_account: stripe_account}
      )
    end
end

app/controllers/vendor_onboarding_controller.rb
class VendorOnboardingController < ApplicationController
  before_action :authenticate_vendor!

  def connect_to_stripe
  end

  def stripe_connect_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to "Sign up", new_vendor_registration_path %>

app/views/invoices/index.html.erb
<h1>INVOICES</h1>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_for @invoice do |f| %>
  <% if @invoice.errors.any? %>
    <div id='error_explanation'>
      <h2>Oops! We couldn't create your invoice.  Please see below.</h2>

      <ul>
        <% @invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :amount %><br>
  <%= f.text_field :amount %><br>

  <%= f.submit 'CREATE INVOICE' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceApp</title>
    <%= csrf_meta_tags %>
    <meta charset='utf-8'>
    <meta content='width=device-width, initial-scale=1' name='viewport'>
    <meta content='Webflow' name='generator'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src='https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js' type='text/javascript'></script>
    <!-- [if lt IE9]><script src='https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js' type='text/javascript'></script><![endif] -->
    <link href='https://daks2k3a4ib2z.cloudfront.net/img/favicon.ico' rel="shortcut icon" type="image/x-icon">
    <link href='https://daks2k3a4ib2z.cloudfront.net/img/webclip.png' rel="apple-touch-icon">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js" type="text/javascript"></script>
    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- [if lte IE9]><script src='https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2.placeholders.min.js'></script><![endif] -->
  </body>
</html>

app/views/subscriptions/confirmation.html.erb
<h1>THANK YOU!</h1>

<div>You should receive a receipt from Stripe,<br>our payment provider, shortly. <br><br>Thanks again!</div>

app/views/subscriptions/new.html.erb
<div id='stripe_error'>
  <noscript>Javascript is not enabled and is required for this form.  First enable it in your web browser settings.</noscript>
</div>

<div class='invoice-bkg'>
  <div class='w-container'>
    <div class='invoice-head'>
      <h1 class='invoice-title'><%= @invoice.name %></h1>
       <div class='invoice-subtitle-blk'><!--%= image_tag 'lock-grey-3.png', class: 'small-lock-icon' %-->
         <div class='invoice-subtitle'>Payment Secured By 128-bit SSL Encryption</div>
       </div>
    </div>
  </div>
  <div class='invoice-flex-cont'>
    <div class='invoice-form'>
      <div class='w-row'>
        <div class='w-col w-col-6'>
          <div class='invoice-form-info'>
            <div class='invoice-about-row w-row'>
              <div class='w-col w-col-2 w-col-small-2 w-col-tiny-2'><img class='invoice-dba-logo' src="https://d3e54v103j8qbb.cloudfront.net/img/image-placeholder.svg"></div>
              <div class='w-col w-col-10 w-col-small-10 w-col-tiny-10'>
                <div class='invoice-about-txt'><%= @business_name %></div>
                <div class='invoice-about-txt-bold'><%= @statement_descriptor %></div>
              </div>
            </div>
            <div class='invoice-about-row w-row'>
              <div class='w-col w-col-2 w-col-small-2 w-col-tiny-2'><!--%= image_tag 'credit-card-1.png', class: 'cred-card-img' %--></div>
              <div class='w-col w-col-10 w-col-small-10 w-col-tiny-10'>
                <div class='invoice-about-txt'>Amount Due</div>
                <div class='invoice-about-txt-bold'><%= number_to_currency(@invoice.amount) %></div>
              </div>
            </div>
            <div class='invoice-about-row w-row'>
              <div class='w-col w-col-2 w-col-small-2 w-col-tiny-2'><!--%= image_tag 'paytype.png', class: 'paytype-img' %--></div>
              <div class='w-col w-col-10 w-col-small-10 w-col-tiny-10'>
                <div class='invoice-about-txt'>Subscription</div>
                <div class='invoice-about-txt-bold'>Monthly</div>
              </div>
            </div>
            <div class='invoice-about-row w-row'>
              <div class='w-col w-col-2 w-col-small-2 w-col-tiny-2'><!--%= image_tag 'descript-grey.png', class: 'paytype-img' %--></div>
              <div class='w-col w-col-10 w-col-small-10 w-col-tiny-10'>
                <div class='invoice-about-txt'>Description</div>
                <div class='invoice-about-txt-bold'><%= simple_format(@invoice.description) %></div>
              </div>
            </div>
            <div class='invoice-about-row invoice-about-row-no-bord w-row'>
              <div class='w-col w-col-2 w-col-small-2 w-col-tiny-2'><!--%= image_tag 'support.png', class: 'support-icon' %--></div>
              <div class='w-col w-col-10 w-col-small-10 w-col-tiny-10'>
                <div class='invoice-about-txt'>Need Help</div>
                <div class='invoice-about-txt-bold'>Contact us: <span class='blue-txt'>support@email.com</span></div>
              </div>
            </div>
          </div>
        </div>
        <div class='w-col w-col-6'>
          <div class='invoice-secure-logo-row w-row'>
           <div class='w-clearfix w-col w-col-9 w-col-small-9 w-col-tiny-9'><!--%= image_tag 'secure-payment.png', class: 'secure-payment-img' %--></div>
           <div class='w-clearfix w-col w-col-3 w-col-small-3 w-col-tiny-3'><!--%= image_tag 'secure-encrypt.png', class: 'secure-encrypt-img' %--></div>
          </div>
        </div>
        <div class='invoice=payment-info-row w-row'>
          <div class='w-col w-col-6 w-col-small-6 w-col-tiny-6'>
           <div class='invoice-pay-info text-block'>PAYMENT INFO</div>
          </div>
          <div class="w-col w-col6 w-col-small-6 w-col-tiny-6"><!--%= image_tag 'creditcards.png', class: 'cred-card-logos-img' %--></div>
        </div>
        <div class='w-form'>
          <%= form_with(model: [@invoice, @subscription], html: {id: 'credit_card_form'}, data: { disable_with: "Please wait..."}) do |f| %>
              <% if @subscription.errors.any? %>
              <!-- Used to display form errors -->
              <div id='card-errors' role='alert'></div>
              <div id='error_explanation'>
                <h2>Oops! We couldn't create your subscription.  Please see below.</h2>

                <ul>
                  <% @subscription.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <label class='invoice-field-label' for='email'>Email Address</label>
            <%= f.text_field :customer_email, class:'invoice-text-field w-input', placeholder: 'name@example.com', required: 'required', autofocus: 'autofocus', maxlength: '256', type: 'email' %>

            <div class='invoice-cred-card-blk'>
              <div class='w-col w-col-6 w-col-small-6 w-col-tiny-6'><label class='invoice-field-label' for='Card-Number'>Card Number</label></div>
              <div class='w-clearfix w-col w-col-6 w-col-small-6 w-col-tiny-6'><!--%= image_tag 'powered_by_stripe.png', class: 'stripe-logo' %--></div>
              <div id='card-element' class='invoice-text-field w-input'>
                <!-- a Stripe Element will be inserted here. -->
              </div>
            </div>

            <div class='invoice-order-btn w-inline-block'>
              <%= button_tag(type: 'submit', class: 'invoice-order-btn w-inline-block invoice-order-btn-txt') do %>
                <span><!--%= image_tag 'lock-white.png', class: 'lock-white-img' %--> PLACE ORDER NOW</span>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class='invoice-footer'>
          <div class='w-row'>
            <div class='w-clearfix w-col w-col-6 w-col-small-6 w-col-tiny-6'>
              <div class='invoice-footer-txt'>Powered by</div>
            </div>
            <div class='w-col w-col-6 w-col-small-6 w-col-tiny-6'><a class='imvoice-footer-logo w-inling-block' href='#'><!--%= image_tag 'logo.png', class: 'logo' %--></a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vendor_onboarding/connect_to_stripe.html.erb
<%= link_to 'CONNECT TO STRIPE', vendor_stripe_connect_omniauth_authorize_path %>

app/views/vendor_onboarding/stripe_connect_confirmation.html.erb
<%= link_to 'CREATE A PAYMENT LINK', new_invoice_path %>